### ISSUE TITLE
kubb/swagger-ts nullable type and possible redundant undefined; (v1.8.5)

### ISSUE THREAD

**Issue by jafin** [kubb-project/kubb#429]
### What is the problem this feature would solve?

given this schema
```yml
properties:
 effectiveDate:
    type: string
    format: date-time
    nullable: true
```

with kubb/swagger-ts generates

```ts
/**
 * @type string | undefined date-time
 */
effectiveDate?: Date | undefined;
```

kubb.config
```ts
 createSwaggerTS({
    output: 'models',
    groupBy: {
        type: 'tag',
    },
    dateType: 'date',
}),
```

The linter will warn that undefined and nullable are redundant.
```ts
Consider removing 'undefined' type or '?' specifier, one of them is redundant. 
[+1 location]sonarlint(typescript:S4782)
```

### What is the feature you are proposing to solve the problem?

Suggestion to removing the `undefined` from the output type.
